name: Coletando dados climáticos

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run data collection script
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: python coletor.py

      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: weather-data
          path: .
  sync-data:
    runs-on: ubuntu-latest
    needs: collect-data
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download data artifact
        uses: actions/download-artifact@v4
        with:
          name: weather-data

      - name: Commit and push new data
        env:
          GITHUB_TOKEN: ${{ secrets.CLIMA_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url --push origin https://rafaelmelom-dev:$GITHUB_TOKEN@github.com/rafaelmelom-dev/ClimaObserver
          git add data_lake/
          if ! git diff --staged --quiet; then
            git commit -m "COLETA AUTOMÁTICA"
            git push
          else
            echo "No new data to commit."
          fi
